---
title: "Dissecting the causal question underlying the association between cancer and ADRD: an opportunity to understand sources of bias"
author: "L. Paloma Rojas-Saunero"
date: ""
output: [html_document]
editor_options: 
  chunk_output_type: console
bibliography: cancer_dementia.bib
---
```{r, echo =  FALSE, message = FALSE, warning = FALSE}
knitr::opts_chunk$set(echo = FALSE, message = FALSE, warning = FALSE)
library(survival)
library(tidyverse)
library(tableone)
library(magrittr)
library(kableExtra)
source(here::here("02_R", "03_descriptives.R"))
source(here::here("02_R", "05_plots.R"))
source(here::here("02_R", "05b_plot_causes_death.R"))
# table_results <- rio::import(here::here("02_R", "table_results.csv"))
# table_results_bounds <- rio::import(here::here("02_R", "table_results_bounds.csv"))
# models <- read_csv(here::here("04_reports", "models.csv")) %>% select(-6)
```


## 1. Introduction

Many observational studies have consistently found that individuals with cancer have a lower risk of developing of Alzheimer´s disease or related dementias (ADRD) when compared to individuals with no history of cancer [@ma2014;@hanson2016;@vanderwillik2018;@ospina2020]. These findings have motivated substantial research toward mechanistic explanations, including searching for and hypothesizing that molecular and genetic mechanisms may explain this association[@behrens2009;@harris2014;@nudelman2019;@Papin2020;@driverbiogeront2014;@olson2019;@li2021;@driverpin12015]. These research inquiries inevitably lead to discussions of repurposing or augmenting current cancer chemotherapeutics for ADRD [@Snyder2017].

Nevertheless, inferring any treatment or mechanistic effects from the observed cancer-ADRD inverse association is not straightforward. Researchers have raised concerns related to the competing event of death, unmeasured confounding, and ascertainment error that could explain these results[@driverbiogeront2014;@ganguli2015]. However, understanding these or other sources of bias first requires making explicit the causal question. Moreover, making explicit the causal question is one step toward tying a research study to a question that is relevant to decision-making[@didelez2016;@labrecque2017]. 
To illustrate the complexities of inferring hypothetical or available treatments’ effects on ADRD from the observed cancer-ADRD association, we focus on a specific question conceptualizing the  Pin1 enzyme as the target of intervention. Previous animal studies have shown that Pin1 enzyme over-expression promotes tumorigenesis, while its down-regulation is attributed to mechanisms that contribute to neurodegeneration and amyloid deposition[@driverpin12015;@angelucci2017;@li2021]. If we one day could develop a drug that increases Pin1 expression specifically in brain tissue in hopes of preventing dementia, we could pose the question as: _What is the effect of this Pin1-targeting drug on the risk of ADRD over time compared to standard treatments?_

To explore how we might learn about this effect using real-world data on cancer and ADRD, we progressively build a causal directed acyclic graph to connect this particular causal question to the observable data and the assumptions we rely on to study the effect. We exemplify different scenarios with data collected from the Rotterdam Study, a population-based cohort study. We describe the challenges and how they translate into the analytic decisions. Last, we discuss how information on mortality and cause of death can provide insight about the direction of some sources of bias.

## 2. Overview of the causal structure

If this hypothetical Pin1-targeting drug was developed, the best way to understand its effect on dementia risk would be to have a well-conducted randomized trial in which we randomize eligible participants in late midlife (e.g., ages 50-60 years) to receive this drug or not, and closely monitor ADRD over a lengthy follow-up. Since this drug is not currently available, at best we can use observational data on Pin1 expression measurements. For example, suppose that a biomarker test was available to measure Pin1 and we measured this biomarker from (stored) baseline blood samples in a population based-cohort that recruited participants in late midlife. 

In the observational setting, confounding could explain the observed association between Pin1 and ADRD. In the directed acyclic graph [@whatif2020] of Figure 1, we present Pin1 expression measured at time $t$ as $P_{t-1}$ and ADRD diagnosis over time as $Y_{t+1}$. Both nodes may share causes $L$, and to assess the causal relationship between $P_{t-1}$ and $Y_{t+1}$ we would require adjusting for $L$. Previous studies have described age, sex, educational level and race/ethnicity as the minimal adjusting set of covariates[@ospina2020]. However, environmental and behavioral factors such as smoking, which are known to cause microenvironmental changes such as inflammation and changes in tissue remodeling, may translate into Pin1 over-expression and are also related to the development of ADRD[ref].

```{tikz, echo = FALSE, fig.cap = "Pin1 as biomarker and risk of dementia"}
\usetikzlibrary{arrows}
\begin{tikzpicture}[node distance=2cm]
\node (p) {$P_{t-1}$};
\node [above of = p, yshift = -0.8cm, xshift = -1cm](l) {$L$};
\node [gray!30, below of = p, yshift = 1cm] (pstar) {$P^*_{t-1}$};
\node [gray!30, right of = p] (dp) {$D_t$};
\node [gray!30, right of = dp] (p2) {$P_t$};
\node [gray!30, below of = p2, yshift = 1cm] (pstar2) {$P^*_t$};
\node [gray!30, right of = p2] (dp2) {$D_{t+1}$};
\node [right of = dp2] (y) {$Y_{t+1}$};
\node [gray!30, below of = dp2, yshift = 1cm, xshift = +1cm](cd) {$C$};
\draw[->, gray!30] (p) to (pstar);
\draw[->, gray!30] (p2) to (pstar2);
\draw[->] (l) -- (p);
\draw[->, gray!30] (l) -- (p2);
\draw[->, gray!30] (l) to (dp);
\draw[->, gray!30] (l) to [out=0,in=90, looseness=0.4] (dp2);
\draw[->] (l) to [out=0,in=90, looseness=0.4] (y);
\draw[->, gray!30] (pstar) -- (dp);
\draw[->, gray!30] (pstar2) -- (dp2);
\draw[->, gray!30] (dp) to [out=-45,in=-135, looseness=0.3] (dp2);
\draw[->, gray!30] (dp) -- (p2);
\draw[->, gray!30] (dp2) -- (y);
\draw[->, gray!30] (cd) -- (dp2);
\draw[->, gray!30] (cd) -- (y);
\draw[->, gray!30, semithick] (p2) to [out=+45,in=+135, looseness=0.3] (y);
\draw[->, semithick] (p) to [out=+45,in=+135, looseness=0.3] (y);
\end{tikzpicture}
```

Currently, Pin1 expression is not an available biomarker for population-based research, so at best we can only rely on a proxy for it. Because Pin1 over-expression is present in tumors, and tumors are only measured through diagnosis, previous studies have considered Pin1 over-expression as the explanation behind the inverse association between cancer diagnosis and ADRD, though Pin1 was not explicitly part of the research question[@ospina2020;@driver2012;@musicco2013;@freedman2016;@bowles2017;@frain2017;@schmidt2017;@sun2020;@ording2020]. Unlike measuring Pin1 at the same time to all participants (thought this would not necessarily mean this would be the ideal time to measure it, we discuss this point further in the discussion section), cancer diagnosis is a time-varying process. We depict this feature in Figure 2, where $P^*_{t-1}$ and $P^*_t$ represent _cancer diagnosis_ over time, the measured proxy of $P_{t-1}$ and $P_t$ respectively. Although this means we would measure the association between cancer diagnosis over time and ADRD in the observed data, we are assuming that the captured effect is only through the pathway that involves Pin1 expression over time. 

```{tikz, echo = FALSE, fig.cap = "Cancer diagnosis as proxy for Pin1 expression"}
\usetikzlibrary{arrows}
\begin{tikzpicture}[node distance=2cm]
\node (p) {$P_{t-1}$};
\node [above of = p, yshift = -0.8cm, xshift = -1cm](l) {$L$};
\node [below of = p, yshift = 1cm] (pstar) {$P^*_{t-1}$};
\node [gray!30, right of = p] (dp) {$D_t$};
\node [right of = dp] (p2) {$P_t$};
\node [below of = p2, yshift = 1cm] (pstar2) {$P^*_t$};
\node [gray!30, right of = p2] (dp2) {$D_{t+1}$};
\node [right of = dp2] (y) {$Y_{t+1}$};
\node [gray!30, below of = dp2, yshift = 1cm, xshift = +1cm](cd) {$C$};
\draw[->] (p) to (pstar);
\draw[->] (p2) to (pstar2);
\draw[->] (l) -- (p);
\draw[->] (l) -- (p2);
\draw[->] (l) to [out=0,in=90, looseness=0.4] (y);
\draw[->, gray!30] (l) to (dp);
\draw[->, gray!30] (l) to [out=0,in=90, looseness=0.4] (dp2);
\draw[->, gray!30] (dp) -- (p2);
\draw[->, gray!30] (pstar) -- (dp);
\draw[->, gray!30] (pstar2) -- (dp2);
\draw[->, gray!30] (dp) to [out=-45,in=-135, looseness=0.3] (dp2);
\draw[->, gray!30] (dp2) -- (y);
\draw[->, gray!30] (cd) -- (dp2);
\draw[->, gray!30] (cd) -- (y);
\draw[->, semithick] (p) to [out=+45,in=+135, looseness=0.3] (y);
\draw[->, semithick] (p2) to [out=+45,in=+135, looseness=0.3] (y);
\end{tikzpicture}
```

A challenge that arises by defining cancer diagnosis as the proxy for Pin1 is defining the time zero, the time where follow-up and screening for ADRD would begin after having the exposure measured. The eligibility criteria to join the study may not align with the time cancer diagnosis is measured. This situation may introduce inmortal-time bias [@hernanInmortal2016]. For example, a study performed using data from the Framingham study [@driver2012] defined the exposed group with cancer as those participants with prevalent or incident cancer diagnosis (alternatively defined as "ever cancer" [@hanson2016]). This meant that a participant who had cancer diagnosis over follow-up contributed all their person-time to the cancer arm, including the time prior to the cancer diagnosis. By defining the exposure after the time of inclusion to the cohort, only participants who remain alive and free of ADRD diagnosis over follow-up can be defined as "ever cancer" [@anderson1983, @hernanInmortal2016].

This problem is avoided by recognizing the time-varying nature of cancer diagnosis. Several studies have considered cancer diagnosis as a time-dependent exposure. In this way, the time prior to cancer diagnosis is allocated to the non-exposed arm, and the time after cancer diagnosis to the exposed arm [@white2013; @hanson2016; @bowles2017]. The price we pay with this approximation is that implicitly, this means that Pin1 would overexpress at the time of cancer diagnosis, which is biologically implausible. Moreover, cancer diagnosis will only be measured in the subset of participants who are alive over follow-up. Thus we included death prior to cancer diagnosis as $D_t$ and an arrow between $D_t$ and $P_t$ that represents a deterministic association such as that $P_t$ is only observed if $D_t$ is zero in Figure 3. In addition, we added an arrow between $L$ and $D_t$, since covariates such as smoking may affect Pin1 over-expression but also affect the risk of death due to other causes such as COPD.

```{tikz, echo = FALSE, fig.cap = "Time-varying cancer diagnosis and inmortal-time bias"}
\usetikzlibrary{arrows}
\begin{tikzpicture}[node distance=2cm]
\node (p) {$P_{t-1}$};
\node [above of = p, yshift = -0.8cm, xshift = -1cm](l) {$L$};
\node [below of = p, yshift = 1cm] (pstar) {$P^*_{t-1}$};
\node [right of = p] (dp) {$D_t$};
\node [right of = dp] (p2) {$P_t$};
\node [below of = p2, yshift = 1cm] (pstar2) {$P^*_t$};
\node [gray!30, right of = p2] (dp2) {$D_{t+1}$};
\node [right of = dp2] (y) {$Y_{t+1}$};
\node [gray!30, below of = dp2, yshift = 1cm, xshift = +1cm](cd) {$C$};
\draw[->] (p) to (pstar);
\draw[->] (p2) to (pstar2);
\draw[->] (l) -- (p);
\draw[->] (l) -- (p2);
\draw[->] (l) to (dp);
\draw[->] (dp) -- (p2);
\draw[->, gray!30] (l) to [out=0,in=90, looseness=0.4] (dp2);
\draw[->] (l) to [out=0,in=90, looseness=0.4] (y);
\draw[->, gray!30] (pstar) -- (dp);
\draw[->, gray!30] (pstar2) -- (dp2);
\draw[->, gray!30] (dp) to [out=-45,in=-135, looseness=0.3] (dp2);
\draw[->, gray!30] (dp2) -- (y);
\draw[->, gray!30] (cd) -- (dp2);
\draw[->, gray!30] (cd) -- (y);
\draw[->, semithick] (p2) to [out=+45,in=+135, looseness=0.3] (y);
\draw[->, semithick] (p) to [out=+45,in=+135, looseness=0.3] (y);
\end{tikzpicture}
```

We now move to the challenge of death as a competing event for ADRD, represented in Figure 5. For interpretability we exclude the time varying process of cancer diagnosis and focus on Pin1 (and cancer diagnosis) as it had been measured in all participants at $t$. Given that some participants may die prior to having a cancer diagnosis over follow-up, we can only have ADRD over follow-up in the individuals who survive long enough to have an ADRD diagnosis. In the causal diagram of Figure 4 we include a node for death after the exposure $P^*t$ has been measured, represented as $D_{t+1}$, this acts as a competing event of $Y_{t+1}$ because if a participant dies prior to ADRD diagnosis, death prevents observing ADRD at future time-points. Furthermore, since $D_{t+1}$ and $Y_{t+1}$ are events related to aging and its consequences, $C$ represents the shared causes of both events such as cardiovascular conditions. We also include an arrow between $L$ and $D_{t+1}$ following the argument discussed previously.

In the scenario where $P_t$ represented the targeted-drug for Pin1, and if this drug had no systemic beneficial or harmful side-effects such as that there is no arrow between $P$ and $D_{t+1}$, a total effect would quantify the effect of $P_t$ on $Y_{t+1}$ that does not include any pathway mediated through $D_{t+1}$[@young2020]. However, in the context of cancer diagnosis as the proxy for Pin1 over-expression, we cannot rule out the effect of cancer diagnosis on death, represented as the arrow between $P^*_t$ and  $D_{t+1}$. In this setting, a total effect of $P_t$ in $Y_{t+1}$ would include the causal pathway mediated by the effect of cancer diagnosis in mortality, which may translate into an inverse association[@young2020]. 

To isolate the direct effect of $P_t$ in $Y_{t+1}$ through measurement of $P^*_t$ we have at least two alternatives of causal questions we can ask. We can either imagine a causal question where we decompose the effect of cancer by the different mechanisms that affect dementia and death separately[@stensrud2020]. Alternatively, we can define an scenario where death could have been prevented. The latter is defined as the controlled direct effect, where death is considered as a censoring event and it relies on the assumption that we have measured all $C$ to block the pathway $Y_{t+1} \leftarrow C  \rightarrow D_{t+1} \rightarrow P^*_t \rightarrow P_t$. Previous studies have defined death as a censoring event [ref], although failed to explicitly define how to relax the independent censoring assumption. Moreover, adjusting for confounders for dementia may represent partially the adjustment for the competing event of death [@young2020], adjusting for baseline covariates may not be sufficient.

```{tikz, echo = FALSE, fig.cap = "Death as a competing event"}
\usetikzlibrary{arrows}
\begin{tikzpicture}[node distance=2cm]
\node [gray!30](p) {$P_{t-1}$};
\node [above of = p, yshift = -0.8cm, xshift = -1cm](l) {$L$};
\node [gray!30, below of = p, yshift = 1cm] (pstar) {$P^*_{t-1}$};
\node [gray!30, right of = p] (dp) {$D_t$};
\node [right of = dp] (p2) {$P_t$};
\node [below of = p2, yshift = 1cm] (pstar2) {$P^*_t$};
\node [right of = p2] (dp2) {$D_{t+1}$};
\node [right of = dp2] (y) {$Y_{t+1}$};
\node [below of = dp2, yshift = 1cm, xshift = +1cm](cd) {$C$};
\draw[->, gray!30] (p) to (pstar);
\draw[->, gray!30] (l) -- (p);
\draw[->, gray!30] (l) to (dp);
\draw[->, gray!30] (pstar) -- (dp);
\draw[->, gray!30] (dp) to [out=-45,in=-135, looseness=0.3] (dp2);
\draw[->, gray!30] (dp) -- (p2);
\draw[->, semithick, gray!30] (p) to [out=+45,in=+135, looseness=0.3] (y);
\draw[->] (p2) to (pstar2);
\draw[->] (dp2) -- (y);
\draw[->] (cd) -- (dp2);
\draw[->] (cd) -- (y);
\draw[->] (l) -- (p2);
\draw[->] (l) to [out=0,in=90, looseness=0.4] (dp2);
\draw[->] (l) to [out=0,in=90, looseness=0.4] (y);
\draw[->] (pstar2) -- (dp2);
\draw[->, semithick] (p2) to [out=+45,in=+135, looseness=0.3] (y);
\end{tikzpicture}
```

To summarize, the complexity of the causal structure that describes the effect of Pin1 through the proxy of cancer diagnosis in the risk of ADRD illustrate the potential sources of bias, as observed in Figure 6. Even so, this is a simplified version since we omitted the time varying nature of all nodes in the graph and other sources of measurement error, and thus are ignoring how feedback loops between them further complicate interpretability and identificability. 

```{tikz, echo = FALSE, fig.cap = "Direct effect of Pin1 in the risk of ADRD"}
\usetikzlibrary{arrows}
\begin{tikzpicture}[node distance=2cm]
\node (p) {$P_{t-1}$};
\node [above of = p, yshift = -0.8cm, xshift = -1cm](l) {$L$};
\node [below of = p, yshift = 1cm] (pstar) {$P^*_{t-1}$};
\node [right of = p] (dp) {$D_t$};
\node [right of = dp] (p2) {$P_t$};
\node [below of = p2, yshift = 1cm] (pstar2) {$P^*_t$};
\node [right of = p2] (dp2) {$D_{t+1}$};
\node [right of = dp2] (y) {$Y_{t+1}$};
\node [below of = dp2, yshift = 1cm, xshift = +1cm](cd) {$C$};
\draw[->] (p) to (pstar);
\draw[->] (l) -- (p);
\draw[->] (l) to (dp);
\draw[->] (pstar) -- (dp);
\draw[->] (dp) to [out=-45,in=-135, looseness=0.3] (dp2);
\draw[->] (dp) -- (p2);
\draw[->, semithick] (p) to [out=+45,in=+135, looseness=0.3] (y);
\draw[->] (p2) to (pstar2);
\draw[->] (dp2) -- (y);
\draw[->] (cd) -- (dp2);
\draw[->] (cd) -- (y);
\draw[->] (l) -- (p2);
\draw[->] (l) to [out=0,in=90, looseness=0.4] (dp2);
\draw[->] (l) to [out=0,in=90, looseness=0.4] (y);
\draw[->] (pstar2) -- (dp2);
\draw[->, semithick] (p2) to [out=+45,in=+135, looseness=0.3] (y);
\end{tikzpicture}
```


We now turn to an application where we show how these challenges translate in analytic decisions, and we will show ways to mitigate or better understand to the best of the available data's abilities.  Nevertheless, we acknowledge that cancer diagnosis represents a complex and heterogenous health condition that exceeds the representation of Pin1 expression, thus, at best we may test the sharp null hypothesis rather than estimating the causal effect of Pin1. In this section we conduct an analysis of the cancer-ADRD association that is structured to the best of the available data's abilities to inform the possible effect of Pin1 on all cause-dementia.

## 4. Application to the Rotterdam Study

We use data collected in the Rotterdam Study, a population-based prospective cohort study among persons living in the Ommoord district in Rotterdam, the Netherlands. Recruitment and initial assessments were held between 1990 and 1993; it was later extended between 2000 and 2001 consisting of individuals who had reached the age of 55 years or who had moved into the study area. Participants from first subcohort had follow-up visits between 1993-1995, 1997-1999, 2002-2005, and 2008-2010, second subcohort had follow-up visits between 2004 and 2005, and between 2011 and 2012[@ikram2020]. All participants had data on incident cancer diagnosis and incident dementia diagnosis through follow-up, collected from medical records of general practitioners (including hospital discharge letters) and through linkage with national registries. Date and cause of death was collected on a weekly basis via municipal population registries. Data on clinical outcomes was available until 2015.

We considered as inclusion criteria being between 60 and 70 years old at study entry, without history of cancer diagnosis, free of cognitive decline or with previous history of dementia. Out of 10998 persons who participated at study entry, `r total_n` were considered eligible. Time to cancer diagnosis, time to dementia diagnosis and death status was measured for all participants. All participants were followed from study entry until dementia diagnosis, death or 20 years after their individual baseline date, whichever occurred first.

### 4.1. Methods

We illustrate the association between cancer and dementia diagnosis under two scenarios. For the first scenario (Model A) we defined cancer proxy as _"cancer ever vs. never"_.This scenario mimics the definition used in previous studies where cancer was defined as a time-independent exposure[@driver2012; @nudelman2014]. We continue with a second scenario (Model B) where cancer diagnosis is a time-varying exposure. The definition represents the setting where all participants are free of cancer at inclusion and over time some participants will have a cancer diagnosis. 

To address confounding we fit inverse probability treatment weights, stabilized and truncated at 99th percentile. Weights for model A were defined as the inverse of the probability of cancer diagnosis conditional on baseline covariates such as age at study entry, sex, educational attainment, cohort, smoking status. In contrast, for Model B weights recreate a pseudopopulation in which time-varying covariates do not predict the risk of cancer diagnosis at time _t_ [@hernan2000]. Time varying covariates included: ...
Further details on modeling specifications and weights assessment are presented as **Supplementary material x**.

To estimate the controlled direct effect of Pin1 in the risk of ADRD, that is in the setting where death could have been prevented, we fit inverse probability censoring weights for death. 



in time-varying settings we compared the complement of a weighted Kaplan-Meier survival estimator in participants with incident cancer vs. no incident of cancer with time indexed in years. The weights in this case are time-varying by follow-up year, defined as a product of the time-fixed IPT weights above and a year-specific inverse probability of censoring (IPC) by death weights.  For an individual still alive in year t, the time t IPC weight is the product of the inverse probability of surviving in each year prior to t, conditional on measured common causes of death and dementia (that is, variables such as C in Figure 4). For an individual who has died by time t, the year t IPC weight is zero.  We estimated survival probabilities using a logistic regression model for death as a function of baseline and time-varying covariates. Baseline covariates included age at study entry, sex, apoe4 status, educational attainment and the time-varying covariates smoking status, systolic blood pressure, BMI and prevalent and incident comorbidities such as: cancer, heart disease, stroke and diabetes. We additionally calculated the controlled direct effect considering death as an unconditional independent censoring event (as if there were no arrows from $C$ to $D_{15}$ and $Y_{20}$) for an illustrative purpose.

Estimates of the controlled direct effect at 20 years of follow-up are presented as risk differences (RD), risk ratios (RR) and hazard ratios (HR). We note that hazards, unlike risks, inherently condition on surviving both dementia and death, as such they will not have a causal interpretation in this case. We present them for comparison against risk ratios.

Since the conditional independent censoring assumption is untestable, we compute Peterson upper and lower bounds to represent: 1) the extreme scenario of independence, that refers to an scenario were those who died would never develop dementia (lower bound) and 2) complete dependency, that refers to an scenario where those who died would have a dementia prior to death (upper bound). The lower bound is calculated with the Aalen-Johansen estimator treating death as a competing event, and the upper bound is calculated with the Kaplan Meier estimator for the combined outcome of dementia or death.

We additionally present the causes of death for participants who developed cancer and for participants free of cancer diagnosis over follow-up. This information provides insights about the association between cancer diagnosis and death and about the potential misclassification of individuals with no cancer diagnosis (cancer as a cause of death).

All 95% confidence intervals were calculated using percentile-based bootstrapping based on 500 bootstrap samples. All analysis were performed using R, code is provided in supplementary material and available in https://github.com/palolili23/2021_cancer_dementia.

